services:
  user_app:
    container_name: hrm_user
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051" # GRPC
      - "8089:8089"
    environment:
      GIN_MODE: ${GIN_MODE:-debug}
    volumes:
      - .:/app
    depends_on:
      - user_postgres
    networks:
      - shared_network

  user_postgres:
    container_name: hrm_user_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - shared_network
      
  adminer:
    container_name: hrm_adminer
    image: adminer
    ports:
      - "81:8080"
    networks:
      - shared_network

volumes:
  data:
    name: hrm_user_data

networks:
  shared_network:
    name: hrm_shared_network
