// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/permission/permission_ext.proto

package permission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserPermsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPermsByUserIDRequest) Reset() {
	*x = DeleteUserPermsByUserIDRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPermsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPermsByUserIDRequest) ProtoMessage() {}

func (x *DeleteUserPermsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPermsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPermsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserPermsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserRolesByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRolesByUserIDRequest) Reset() {
	*x = DeleteUserRolesByUserIDRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRolesByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRolesByUserIDRequest) ProtoMessage() {}

func (x *DeleteUserRolesByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRolesByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRolesByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteUserRolesByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserPermsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PermIds       []string               `protobuf:"bytes,2,rep,name=perm_ids,json=permIds,proto3" json:"perm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPermsRequest) Reset() {
	*x = UpdateUserPermsRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPermsRequest) ProtoMessage() {}

func (x *UpdateUserPermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPermsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPermsRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPermsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPermsRequest) GetPermIds() []string {
	if x != nil {
		return x.PermIds
	}
	return nil
}

type UpdateUserPermsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPermsResponse) Reset() {
	*x = UpdateUserPermsResponse{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPermsResponse) ProtoMessage() {}

func (x *UpdateUserPermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPermsResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPermsResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserPermsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRolesRequest) Reset() {
	*x = UpdateUserRolesRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRolesRequest) ProtoMessage() {}

func (x *UpdateUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRolesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRolesRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type UpdateUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRolesResponse) Reset() {
	*x = UpdateUserRolesResponse{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRolesResponse) ProtoMessage() {}

func (x *UpdateUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRolesResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRolesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserPermsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermsRequest) Reset() {
	*x = GetUserPermsRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermsRequest) ProtoMessage() {}

func (x *GetUserPermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermsRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPermsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPermsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perms         []*PermExt             `protobuf:"bytes,1,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermsResponse) Reset() {
	*x = GetUserPermsResponse{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermsResponse) ProtoMessage() {}

func (x *GetUserPermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermsResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserPermsResponse) GetPerms() []*PermExt {
	if x != nil {
		return x.Perms
	}
	return nil
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleExt             `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRolesResponse) GetRoles() []*RoleExt {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RoleExt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleExt) Reset() {
	*x = RoleExt{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleExt) ProtoMessage() {}

func (x *RoleExt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleExt.ProtoReflect.Descriptor instead.
func (*RoleExt) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{10}
}

func (x *RoleExt) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RoleExt) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleExt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleExt) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *RoleExt) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *RoleExt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleExt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PermExt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermExt) Reset() {
	*x = PermExt{}
	mi := &file_proto_permission_permission_ext_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermExt) ProtoMessage() {}

func (x *PermExt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_ext_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermExt.ProtoReflect.Descriptor instead.
func (*PermExt) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_ext_proto_rawDescGZIP(), []int{11}
}

func (x *PermExt) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PermExt) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermExt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermExt) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

var File_proto_permission_permission_ext_proto protoreflect.FileDescriptor

const file_proto_permission_permission_ext_proto_rawDesc = "" +
	"\n" +
	"%proto/permission/permission_ext.proto\x12\n" +
	"permission\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"9\n" +
	"\x1eDeleteUserPermsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1eDeleteUserRolesByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x16UpdateUserPermsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bperm_ids\x18\x02 \x03(\tR\apermIds\"3\n" +
	"\x17UpdateUserPermsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x16UpdateUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"3\n" +
	"\x17UpdateUserRolesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13GetUserPermsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x14GetUserPermsResponse\x12)\n" +
	"\x05perms\x18\x01 \x03(\v2\x13.permission.PermExtR\x05perms\"A\n" +
	"\x14GetUserRolesResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.permission.RoleExtR\x05roles\"\xab\x02\n" +
	"\aRoleExt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x05color\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x01\n" +
	"\aPermExt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription2\xa8\x04\n" +
	"\n" +
	"ExtService\x12]\n" +
	"\x17DeleteUserPermsByUserID\x12*.permission.DeleteUserPermsByUserIDRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x17DeleteUserRolesByUserID\x12*.permission.DeleteUserRolesByUserIDRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x0fUpdateUserPerms\x12\".permission.UpdateUserPermsRequest\x1a#.permission.UpdateUserPermsResponse\x12Z\n" +
	"\x0fUpdateUserRoles\x12\".permission.UpdateUserRolesRequest\x1a#.permission.UpdateUserRolesResponse\x12Q\n" +
	"\fGetUserPerms\x12\x1f.permission.GetUserPermsRequest\x1a .permission.GetUserPermsResponse\x12Q\n" +
	"\fGetUserRoles\x12\x1f.permission.GetUserRolesRequest\x1a .permission.GetUserRolesResponseB\x12Z\x10proto/permissionb\x06proto3"

var (
	file_proto_permission_permission_ext_proto_rawDescOnce sync.Once
	file_proto_permission_permission_ext_proto_rawDescData []byte
)

func file_proto_permission_permission_ext_proto_rawDescGZIP() []byte {
	file_proto_permission_permission_ext_proto_rawDescOnce.Do(func() {
		file_proto_permission_permission_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_permission_permission_ext_proto_rawDesc), len(file_proto_permission_permission_ext_proto_rawDesc)))
	})
	return file_proto_permission_permission_ext_proto_rawDescData
}

var file_proto_permission_permission_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_permission_permission_ext_proto_goTypes = []any{
	(*DeleteUserPermsByUserIDRequest)(nil), // 0: permission.DeleteUserPermsByUserIDRequest
	(*DeleteUserRolesByUserIDRequest)(nil), // 1: permission.DeleteUserRolesByUserIDRequest
	(*UpdateUserPermsRequest)(nil),         // 2: permission.UpdateUserPermsRequest
	(*UpdateUserPermsResponse)(nil),        // 3: permission.UpdateUserPermsResponse
	(*UpdateUserRolesRequest)(nil),         // 4: permission.UpdateUserRolesRequest
	(*UpdateUserRolesResponse)(nil),        // 5: permission.UpdateUserRolesResponse
	(*GetUserPermsRequest)(nil),            // 6: permission.GetUserPermsRequest
	(*GetUserRolesRequest)(nil),            // 7: permission.GetUserRolesRequest
	(*GetUserPermsResponse)(nil),           // 8: permission.GetUserPermsResponse
	(*GetUserRolesResponse)(nil),           // 9: permission.GetUserRolesResponse
	(*RoleExt)(nil),                        // 10: permission.RoleExt
	(*PermExt)(nil),                        // 11: permission.PermExt
	(*wrapperspb.StringValue)(nil),         // 12: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 14: google.protobuf.Empty
}
var file_proto_permission_permission_ext_proto_depIdxs = []int32{
	11, // 0: permission.GetUserPermsResponse.perms:type_name -> permission.PermExt
	10, // 1: permission.GetUserRolesResponse.roles:type_name -> permission.RoleExt
	12, // 2: permission.RoleExt.color:type_name -> google.protobuf.StringValue
	12, // 3: permission.RoleExt.description:type_name -> google.protobuf.StringValue
	13, // 4: permission.RoleExt.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: permission.RoleExt.updated_at:type_name -> google.protobuf.Timestamp
	12, // 6: permission.PermExt.description:type_name -> google.protobuf.StringValue
	0,  // 7: permission.ExtService.DeleteUserPermsByUserID:input_type -> permission.DeleteUserPermsByUserIDRequest
	1,  // 8: permission.ExtService.DeleteUserRolesByUserID:input_type -> permission.DeleteUserRolesByUserIDRequest
	2,  // 9: permission.ExtService.UpdateUserPerms:input_type -> permission.UpdateUserPermsRequest
	4,  // 10: permission.ExtService.UpdateUserRoles:input_type -> permission.UpdateUserRolesRequest
	6,  // 11: permission.ExtService.GetUserPerms:input_type -> permission.GetUserPermsRequest
	7,  // 12: permission.ExtService.GetUserRoles:input_type -> permission.GetUserRolesRequest
	14, // 13: permission.ExtService.DeleteUserPermsByUserID:output_type -> google.protobuf.Empty
	14, // 14: permission.ExtService.DeleteUserRolesByUserID:output_type -> google.protobuf.Empty
	3,  // 15: permission.ExtService.UpdateUserPerms:output_type -> permission.UpdateUserPermsResponse
	5,  // 16: permission.ExtService.UpdateUserRoles:output_type -> permission.UpdateUserRolesResponse
	8,  // 17: permission.ExtService.GetUserPerms:output_type -> permission.GetUserPermsResponse
	9,  // 18: permission.ExtService.GetUserRoles:output_type -> permission.GetUserRolesResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_permission_permission_ext_proto_init() }
func file_proto_permission_permission_ext_proto_init() {
	if File_proto_permission_permission_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_permission_permission_ext_proto_rawDesc), len(file_proto_permission_permission_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_permission_permission_ext_proto_goTypes,
		DependencyIndexes: file_proto_permission_permission_ext_proto_depIdxs,
		MessageInfos:      file_proto_permission_permission_ext_proto_msgTypes,
	}.Build()
	File_proto_permission_permission_ext_proto = out.File
	file_proto_permission_permission_ext_proto_goTypes = nil
	file_proto_permission_permission_ext_proto_depIdxs = nil
}
