// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/permission/permission.proto

package permission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPermRequest_View int32

const (
	GetPermRequest_VIEW_UNSPECIFIED GetPermRequest_View = 0
	GetPermRequest_BASIC            GetPermRequest_View = 1
	GetPermRequest_WITH_EDGE_IDS    GetPermRequest_View = 2
)

// Enum value maps for GetPermRequest_View.
var (
	GetPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetPermRequest_View) Enum() *GetPermRequest_View {
	p := new(GetPermRequest_View)
	*p = x
	return p
}

func (x GetPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[0].Descriptor()
}

func (GetPermRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[0]
}

func (x GetPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPermRequest_View.Descriptor instead.
func (GetPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{1, 0}
}

type ListPermRequest_View int32

const (
	ListPermRequest_VIEW_UNSPECIFIED ListPermRequest_View = 0
	ListPermRequest_BASIC            ListPermRequest_View = 1
	ListPermRequest_WITH_EDGE_IDS    ListPermRequest_View = 2
)

// Enum value maps for ListPermRequest_View.
var (
	ListPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListPermRequest_View) Enum() *ListPermRequest_View {
	p := new(ListPermRequest_View)
	*p = x
	return p
}

func (x ListPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[1].Descriptor()
}

func (ListPermRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[1]
}

func (x ListPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPermRequest_View.Descriptor instead.
func (ListPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{2, 0}
}

type GetPermGroupRequest_View int32

const (
	GetPermGroupRequest_VIEW_UNSPECIFIED GetPermGroupRequest_View = 0
	GetPermGroupRequest_BASIC            GetPermGroupRequest_View = 1
	GetPermGroupRequest_WITH_EDGE_IDS    GetPermGroupRequest_View = 2
)

// Enum value maps for GetPermGroupRequest_View.
var (
	GetPermGroupRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetPermGroupRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetPermGroupRequest_View) Enum() *GetPermGroupRequest_View {
	p := new(GetPermGroupRequest_View)
	*p = x
	return p
}

func (x GetPermGroupRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPermGroupRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[2].Descriptor()
}

func (GetPermGroupRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[2]
}

func (x GetPermGroupRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPermGroupRequest_View.Descriptor instead.
func (GetPermGroupRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{5, 0}
}

type ListPermGroupRequest_View int32

const (
	ListPermGroupRequest_VIEW_UNSPECIFIED ListPermGroupRequest_View = 0
	ListPermGroupRequest_BASIC            ListPermGroupRequest_View = 1
	ListPermGroupRequest_WITH_EDGE_IDS    ListPermGroupRequest_View = 2
)

// Enum value maps for ListPermGroupRequest_View.
var (
	ListPermGroupRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListPermGroupRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListPermGroupRequest_View) Enum() *ListPermGroupRequest_View {
	p := new(ListPermGroupRequest_View)
	*p = x
	return p
}

func (x ListPermGroupRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPermGroupRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[3].Descriptor()
}

func (ListPermGroupRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[3]
}

func (x ListPermGroupRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPermGroupRequest_View.Descriptor instead.
func (ListPermGroupRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{6, 0}
}

type GetRoleRequest_View int32

const (
	GetRoleRequest_VIEW_UNSPECIFIED GetRoleRequest_View = 0
	GetRoleRequest_BASIC            GetRoleRequest_View = 1
	GetRoleRequest_WITH_EDGE_IDS    GetRoleRequest_View = 2
)

// Enum value maps for GetRoleRequest_View.
var (
	GetRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetRoleRequest_View) Enum() *GetRoleRequest_View {
	p := new(GetRoleRequest_View)
	*p = x
	return p
}

func (x GetRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[4].Descriptor()
}

func (GetRoleRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[4]
}

func (x GetRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRoleRequest_View.Descriptor instead.
func (GetRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{10, 0}
}

type ListRoleRequest_View int32

const (
	ListRoleRequest_VIEW_UNSPECIFIED ListRoleRequest_View = 0
	ListRoleRequest_BASIC            ListRoleRequest_View = 1
	ListRoleRequest_WITH_EDGE_IDS    ListRoleRequest_View = 2
)

// Enum value maps for ListRoleRequest_View.
var (
	ListRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListRoleRequest_View) Enum() *ListRoleRequest_View {
	p := new(ListRoleRequest_View)
	*p = x
	return p
}

func (x ListRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[5].Descriptor()
}

func (ListRoleRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[5]
}

func (x ListRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRoleRequest_View.Descriptor instead.
func (ListRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{13, 0}
}

type GetUserPermRequest_View int32

const (
	GetUserPermRequest_VIEW_UNSPECIFIED GetUserPermRequest_View = 0
	GetUserPermRequest_BASIC            GetUserPermRequest_View = 1
	GetUserPermRequest_WITH_EDGE_IDS    GetUserPermRequest_View = 2
)

// Enum value maps for GetUserPermRequest_View.
var (
	GetUserPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetUserPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetUserPermRequest_View) Enum() *GetUserPermRequest_View {
	p := new(GetUserPermRequest_View)
	*p = x
	return p
}

func (x GetUserPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[6].Descriptor()
}

func (GetUserPermRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[6]
}

func (x GetUserPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserPermRequest_View.Descriptor instead.
func (GetUserPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{19, 0}
}

type ListUserPermRequest_View int32

const (
	ListUserPermRequest_VIEW_UNSPECIFIED ListUserPermRequest_View = 0
	ListUserPermRequest_BASIC            ListUserPermRequest_View = 1
	ListUserPermRequest_WITH_EDGE_IDS    ListUserPermRequest_View = 2
)

// Enum value maps for ListUserPermRequest_View.
var (
	ListUserPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListUserPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListUserPermRequest_View) Enum() *ListUserPermRequest_View {
	p := new(ListUserPermRequest_View)
	*p = x
	return p
}

func (x ListUserPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListUserPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[7].Descriptor()
}

func (ListUserPermRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[7]
}

func (x ListUserPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListUserPermRequest_View.Descriptor instead.
func (ListUserPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{22, 0}
}

type GetUserRoleRequest_View int32

const (
	GetUserRoleRequest_VIEW_UNSPECIFIED GetUserRoleRequest_View = 0
	GetUserRoleRequest_BASIC            GetUserRoleRequest_View = 1
	GetUserRoleRequest_WITH_EDGE_IDS    GetUserRoleRequest_View = 2
)

// Enum value maps for GetUserRoleRequest_View.
var (
	GetUserRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetUserRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetUserRoleRequest_View) Enum() *GetUserRoleRequest_View {
	p := new(GetUserRoleRequest_View)
	*p = x
	return p
}

func (x GetUserRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[8].Descriptor()
}

func (GetUserRoleRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[8]
}

func (x GetUserRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserRoleRequest_View.Descriptor instead.
func (GetUserRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{28, 0}
}

type ListUserRoleRequest_View int32

const (
	ListUserRoleRequest_VIEW_UNSPECIFIED ListUserRoleRequest_View = 0
	ListUserRoleRequest_BASIC            ListUserRoleRequest_View = 1
	ListUserRoleRequest_WITH_EDGE_IDS    ListUserRoleRequest_View = 2
)

// Enum value maps for ListUserRoleRequest_View.
var (
	ListUserRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListUserRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListUserRoleRequest_View) Enum() *ListUserRoleRequest_View {
	p := new(ListUserRoleRequest_View)
	*p = x
	return p
}

func (x ListUserRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListUserRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_permission_permission_proto_enumTypes[9].Descriptor()
}

func (ListUserRoleRequest_View) Type() protoreflect.EnumType {
	return &file_proto_permission_permission_proto_enumTypes[9]
}

func (x ListUserRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListUserRoleRequest_View.Descriptor instead.
func (ListUserRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{31, 0}
}

type Perm struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Group         *PermGroup              `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Roles         []*Role                 `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	UserPerms     []*UserPerm             `protobuf:"bytes,7,rep,name=user_perms,json=userPerms,proto3" json:"user_perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Perm) Reset() {
	*x = Perm{}
	mi := &file_proto_permission_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perm) ProtoMessage() {}

func (x *Perm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perm.ProtoReflect.Descriptor instead.
func (*Perm) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Perm) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Perm) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Perm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Perm) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Perm) GetGroup() *PermGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Perm) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Perm) GetUserPerms() []*UserPerm {
	if x != nil {
		return x.UserPerms
	}
	return nil
}

type GetPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetPermRequest_View    `protobuf:"varint,2,opt,name=view,proto3,enum=permission.GetPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermRequest) Reset() {
	*x = GetPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermRequest) ProtoMessage() {}

func (x *GetPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermRequest.ProtoReflect.Descriptor instead.
func (*GetPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{1}
}

func (x *GetPermRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetPermRequest) GetView() GetPermRequest_View {
	if x != nil {
		return x.View
	}
	return GetPermRequest_VIEW_UNSPECIFIED
}

type ListPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListPermRequest_View   `protobuf:"varint,3,opt,name=view,proto3,enum=permission.ListPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermRequest) Reset() {
	*x = ListPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermRequest) ProtoMessage() {}

func (x *ListPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermRequest.ProtoReflect.Descriptor instead.
func (*ListPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{2}
}

func (x *ListPermRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermRequest) GetView() ListPermRequest_View {
	if x != nil {
		return x.View
	}
	return ListPermRequest_VIEW_UNSPECIFIED
}

type ListPermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermList      []*Perm                `protobuf:"bytes,1,rep,name=perm_list,json=permList,proto3" json:"perm_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermResponse) Reset() {
	*x = ListPermResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermResponse) ProtoMessage() {}

func (x *ListPermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermResponse.ProtoReflect.Descriptor instead.
func (*ListPermResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{3}
}

func (x *ListPermResponse) GetPermList() []*Perm {
	if x != nil {
		return x.PermList
	}
	return nil
}

func (x *ListPermResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PermGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Perms         []*Perm                `protobuf:"bytes,4,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermGroup) Reset() {
	*x = PermGroup{}
	mi := &file_proto_permission_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGroup) ProtoMessage() {}

func (x *PermGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGroup.ProtoReflect.Descriptor instead.
func (*PermGroup) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{4}
}

func (x *PermGroup) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PermGroup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermGroup) GetPerms() []*Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

type GetPermGroupRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            []byte                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetPermGroupRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=permission.GetPermGroupRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermGroupRequest) Reset() {
	*x = GetPermGroupRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermGroupRequest) ProtoMessage() {}

func (x *GetPermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermGroupRequest.ProtoReflect.Descriptor instead.
func (*GetPermGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{5}
}

func (x *GetPermGroupRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetPermGroupRequest) GetView() GetPermGroupRequest_View {
	if x != nil {
		return x.View
	}
	return GetPermGroupRequest_VIEW_UNSPECIFIED
}

type ListPermGroupRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PageSize      int32                     `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                    `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListPermGroupRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=permission.ListPermGroupRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermGroupRequest) Reset() {
	*x = ListPermGroupRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermGroupRequest) ProtoMessage() {}

func (x *ListPermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermGroupRequest.ProtoReflect.Descriptor instead.
func (*ListPermGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{6}
}

func (x *ListPermGroupRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermGroupRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermGroupRequest) GetView() ListPermGroupRequest_View {
	if x != nil {
		return x.View
	}
	return ListPermGroupRequest_VIEW_UNSPECIFIED
}

type ListPermGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermGroupList []*PermGroup           `protobuf:"bytes,1,rep,name=perm_group_list,json=permGroupList,proto3" json:"perm_group_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermGroupResponse) Reset() {
	*x = ListPermGroupResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermGroupResponse) ProtoMessage() {}

func (x *ListPermGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermGroupResponse.ProtoReflect.Descriptor instead.
func (*ListPermGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{7}
}

func (x *ListPermGroupResponse) GetPermGroupList() []*PermGroup {
	if x != nil {
		return x.PermGroupList
	}
	return nil
}

func (x *ListPermGroupResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Perms         []*Perm                 `protobuf:"bytes,8,rep,name=perms,proto3" json:"perms,omitempty"`
	UserRoles     []*UserRole             `protobuf:"bytes,9,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_permission_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{8}
}

func (x *Role) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Role) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Role) GetPerms() []*Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *Role) GetUserRoles() []*UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetRoleRequest_View    `protobuf:"varint,2,opt,name=view,proto3,enum=permission.GetRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoleRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetRoleRequest) GetView() GetRoleRequest_View {
	if x != nil {
		return x.View
	}
	return GetRoleRequest_VIEW_UNSPECIFIED
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRoleRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListRoleRequest_View   `protobuf:"varint,3,opt,name=view,proto3,enum=permission.ListRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{13}
}

func (x *ListRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleRequest) GetView() ListRoleRequest_View {
	if x != nil {
		return x.View
	}
	return ListRoleRequest_VIEW_UNSPECIFIED
}

type ListRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleList      []*Role                `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResponse) Reset() {
	*x = ListRoleResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResponse) ProtoMessage() {}

func (x *ListRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResponse.ProtoReflect.Descriptor instead.
func (*ListRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{14}
}

func (x *ListRoleResponse) GetRoleList() []*Role {
	if x != nil {
		return x.RoleList
	}
	return nil
}

func (x *ListRoleResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateRoleRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRolesRequest) Reset() {
	*x = BatchCreateRolesRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRolesRequest) ProtoMessage() {}

func (x *BatchCreateRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRolesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{15}
}

func (x *BatchCreateRolesRequest) GetRequests() []*CreateRoleRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRolesResponse) Reset() {
	*x = BatchCreateRolesResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRolesResponse) ProtoMessage() {}

func (x *BatchCreateRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRolesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreateRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserPerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PermId        []byte                 `protobuf:"bytes,3,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Perm          *Perm                  `protobuf:"bytes,6,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPerm) Reset() {
	*x = UserPerm{}
	mi := &file_proto_permission_permission_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPerm) ProtoMessage() {}

func (x *UserPerm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPerm.ProtoReflect.Descriptor instead.
func (*UserPerm) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{17}
}

func (x *UserPerm) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserPerm) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPerm) GetPermId() []byte {
	if x != nil {
		return x.PermId
	}
	return nil
}

func (x *UserPerm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserPerm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserPerm) GetPerm() *Perm {
	if x != nil {
		return x.Perm
	}
	return nil
}

type CreateUserPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPerm      *UserPerm              `protobuf:"bytes,1,opt,name=user_perm,json=userPerm,proto3" json:"user_perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserPermRequest) Reset() {
	*x = CreateUserPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPermRequest) ProtoMessage() {}

func (x *CreateUserPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPermRequest.ProtoReflect.Descriptor instead.
func (*CreateUserPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUserPermRequest) GetUserPerm() *UserPerm {
	if x != nil {
		return x.UserPerm
	}
	return nil
}

type GetUserPermRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetUserPermRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=permission.GetUserPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermRequest) Reset() {
	*x = GetUserPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermRequest) ProtoMessage() {}

func (x *GetUserPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserPermRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetUserPermRequest) GetView() GetUserPermRequest_View {
	if x != nil {
		return x.View
	}
	return GetUserPermRequest_VIEW_UNSPECIFIED
}

type UpdateUserPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPerm      *UserPerm              `protobuf:"bytes,1,opt,name=user_perm,json=userPerm,proto3" json:"user_perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPermRequest) Reset() {
	*x = UpdateUserPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPermRequest) ProtoMessage() {}

func (x *UpdateUserPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPermRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserPermRequest) GetUserPerm() *UserPerm {
	if x != nil {
		return x.UserPerm
	}
	return nil
}

type DeleteUserPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPermRequest) Reset() {
	*x = DeleteUserPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPermRequest) ProtoMessage() {}

func (x *DeleteUserPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPermRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteUserPermRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListUserPermRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PageSize      int32                    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListUserPermRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=permission.ListUserPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPermRequest) Reset() {
	*x = ListUserPermRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPermRequest) ProtoMessage() {}

func (x *ListUserPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPermRequest.ProtoReflect.Descriptor instead.
func (*ListUserPermRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{22}
}

func (x *ListUserPermRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserPermRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUserPermRequest) GetView() ListUserPermRequest_View {
	if x != nil {
		return x.View
	}
	return ListUserPermRequest_VIEW_UNSPECIFIED
}

type ListUserPermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPermList  []*UserPerm            `protobuf:"bytes,1,rep,name=user_perm_list,json=userPermList,proto3" json:"user_perm_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPermResponse) Reset() {
	*x = ListUserPermResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPermResponse) ProtoMessage() {}

func (x *ListUserPermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPermResponse.ProtoReflect.Descriptor instead.
func (*ListUserPermResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{23}
}

func (x *ListUserPermResponse) GetUserPermList() []*UserPerm {
	if x != nil {
		return x.UserPermList
	}
	return nil
}

func (x *ListUserPermResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateUserPermsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Requests      []*CreateUserPermRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUserPermsRequest) Reset() {
	*x = BatchCreateUserPermsRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUserPermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUserPermsRequest) ProtoMessage() {}

func (x *BatchCreateUserPermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUserPermsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateUserPermsRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{24}
}

func (x *BatchCreateUserPermsRequest) GetRequests() []*CreateUserPermRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateUserPermsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPerms     []*UserPerm            `protobuf:"bytes,1,rep,name=user_perms,json=userPerms,proto3" json:"user_perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUserPermsResponse) Reset() {
	*x = BatchCreateUserPermsResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUserPermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUserPermsResponse) ProtoMessage() {}

func (x *BatchCreateUserPermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUserPermsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateUserPermsResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{25}
}

func (x *BatchCreateUserPermsResponse) GetUserPerms() []*UserPerm {
	if x != nil {
		return x.UserPerms
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        []byte                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Role          *Role                  `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_proto_permission_permission_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{26}
}

func (x *UserRole) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRole) GetRoleId() []byte {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *UserRole) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserRole) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserRole) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type CreateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      *UserRole              `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRoleRequest) Reset() {
	*x = CreateUserRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRoleRequest) ProtoMessage() {}

func (x *CreateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{27}
}

func (x *CreateUserRoleRequest) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

type GetUserRoleRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetUserRoleRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=permission.GetUserRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoleRequest) Reset() {
	*x = GetUserRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleRequest) ProtoMessage() {}

func (x *GetUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserRoleRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetUserRoleRequest) GetView() GetUserRoleRequest_View {
	if x != nil {
		return x.View
	}
	return GetUserRoleRequest_VIEW_UNSPECIFIED
}

type UpdateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      *UserRole              `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleRequest) Reset() {
	*x = UpdateUserRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleRequest) ProtoMessage() {}

func (x *UpdateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateUserRoleRequest) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

type DeleteUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRoleRequest) Reset() {
	*x = DeleteUserRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRoleRequest) ProtoMessage() {}

func (x *DeleteUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteUserRoleRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListUserRoleRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PageSize      int32                    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListUserRoleRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=permission.ListUserRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoleRequest) Reset() {
	*x = ListUserRoleRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleRequest) ProtoMessage() {}

func (x *ListUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleRequest.ProtoReflect.Descriptor instead.
func (*ListUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{31}
}

func (x *ListUserRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserRoleRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUserRoleRequest) GetView() ListUserRoleRequest_View {
	if x != nil {
		return x.View
	}
	return ListUserRoleRequest_VIEW_UNSPECIFIED
}

type ListUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoleList  []*UserRole            `protobuf:"bytes,1,rep,name=user_role_list,json=userRoleList,proto3" json:"user_role_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoleResponse) Reset() {
	*x = ListUserRoleResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleResponse) ProtoMessage() {}

func (x *ListUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleResponse.ProtoReflect.Descriptor instead.
func (*ListUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{32}
}

func (x *ListUserRoleResponse) GetUserRoleList() []*UserRole {
	if x != nil {
		return x.UserRoleList
	}
	return nil
}

func (x *ListUserRoleResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateUserRolesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Requests      []*CreateUserRoleRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUserRolesRequest) Reset() {
	*x = BatchCreateUserRolesRequest{}
	mi := &file_proto_permission_permission_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUserRolesRequest) ProtoMessage() {}

func (x *BatchCreateUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUserRolesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{33}
}

func (x *BatchCreateUserRolesRequest) GetRequests() []*CreateUserRoleRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []*UserRole            `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateUserRolesResponse) Reset() {
	*x = BatchCreateUserRolesResponse{}
	mi := &file_proto_permission_permission_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateUserRolesResponse) ProtoMessage() {}

func (x *BatchCreateUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_permission_permission_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateUserRolesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_permission_permission_proto_rawDescGZIP(), []int{34}
}

func (x *BatchCreateUserRolesResponse) GetUserRoles() []*UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

var File_proto_permission_permission_proto protoreflect.FileDescriptor

const file_proto_permission_permission_proto_rawDesc = "" +
	"\n" +
	"!proto/permission/permission.proto\x12\n" +
	"permission\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x88\x02\n" +
	"\x04Perm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12+\n" +
	"\x05group\x18\x05 \x01(\v2\x15.permission.PermGroupR\x05group\x12&\n" +
	"\x05roles\x18\x06 \x03(\v2\x10.permission.RoleR\x05roles\x123\n" +
	"\n" +
	"user_perms\x18\a \x03(\v2\x14.permission.UserPermR\tuserPerms\"\x91\x01\n" +
	"\x0eGetPermRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x123\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1f.permission.GetPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"\xbf\x01\n" +
	"\x0fListPermRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x124\n" +
	"\x04view\x18\x03 \x01(\x0e2 .permission.ListPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"i\n" +
	"\x10ListPermResponse\x12-\n" +
	"\tperm_list\x18\x01 \x03(\v2\x10.permission.PermR\bpermList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"k\n" +
	"\tPermGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\x05perms\x18\x04 \x03(\v2\x10.permission.PermR\x05perms\"\x9b\x01\n" +
	"\x13GetPermGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x128\n" +
	"\x04view\x18\x02 \x01(\x0e2$.permission.GetPermGroupRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"\xc9\x01\n" +
	"\x14ListPermGroupRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x129\n" +
	"\x04view\x18\x03 \x01(\x0e2%.permission.ListPermGroupRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"~\n" +
	"\x15ListPermGroupResponse\x12=\n" +
	"\x0fperm_group_list\x18\x01 \x03(\v2\x15.permission.PermGroupR\rpermGroupList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x03\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x05color\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12&\n" +
	"\x05perms\x18\b \x03(\v2\x10.permission.PermR\x05perms\x123\n" +
	"\n" +
	"user_roles\x18\t \x03(\v2\x14.permission.UserRoleR\tuserRoles\"9\n" +
	"\x11CreateRoleRequest\x12$\n" +
	"\x04role\x18\x01 \x01(\v2\x10.permission.RoleR\x04role\"\x91\x01\n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x123\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1f.permission.GetRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"9\n" +
	"\x11UpdateRoleRequest\x12$\n" +
	"\x04role\x18\x01 \x01(\v2\x10.permission.RoleR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xbf\x01\n" +
	"\x0fListRoleRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x124\n" +
	"\x04view\x18\x03 \x01(\x0e2 .permission.ListRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"i\n" +
	"\x10ListRoleResponse\x12-\n" +
	"\trole_list\x18\x01 \x03(\v2\x10.permission.RoleR\broleList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"T\n" +
	"\x17BatchCreateRolesRequest\x129\n" +
	"\brequests\x18\x01 \x03(\v2\x1d.permission.CreateRoleRequestR\brequests\"B\n" +
	"\x18BatchCreateRolesResponse\x12&\n" +
	"\x05roles\x18\x01 \x03(\v2\x10.permission.RoleR\x05roles\"\xe8\x01\n" +
	"\bUserPerm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aperm_id\x18\x03 \x01(\fR\x06permId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x04perm\x18\x06 \x01(\v2\x10.permission.PermR\x04perm\"J\n" +
	"\x15CreateUserPermRequest\x121\n" +
	"\tuser_perm\x18\x01 \x01(\v2\x14.permission.UserPermR\buserPerm\"\x99\x01\n" +
	"\x12GetUserPermRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x127\n" +
	"\x04view\x18\x02 \x01(\x0e2#.permission.GetUserPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"J\n" +
	"\x15UpdateUserPermRequest\x121\n" +
	"\tuser_perm\x18\x01 \x01(\v2\x14.permission.UserPermR\buserPerm\"'\n" +
	"\x15DeleteUserPermRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc7\x01\n" +
	"\x13ListUserPermRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x128\n" +
	"\x04view\x18\x03 \x01(\x0e2$.permission.ListUserPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"z\n" +
	"\x14ListUserPermResponse\x12:\n" +
	"\x0euser_perm_list\x18\x01 \x03(\v2\x14.permission.UserPermR\fuserPermList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\\\n" +
	"\x1bBatchCreateUserPermsRequest\x12=\n" +
	"\brequests\x18\x01 \x03(\v2!.permission.CreateUserPermRequestR\brequests\"S\n" +
	"\x1cBatchCreateUserPermsResponse\x123\n" +
	"\n" +
	"user_perms\x18\x01 \x03(\v2\x14.permission.UserPermR\tuserPerms\"\xe8\x01\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\fR\x06roleId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x04role\x18\x06 \x01(\v2\x10.permission.RoleR\x04role\"J\n" +
	"\x15CreateUserRoleRequest\x121\n" +
	"\tuser_role\x18\x01 \x01(\v2\x14.permission.UserRoleR\buserRole\"\x99\x01\n" +
	"\x12GetUserRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x127\n" +
	"\x04view\x18\x02 \x01(\x0e2#.permission.GetUserRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"J\n" +
	"\x15UpdateUserRoleRequest\x121\n" +
	"\tuser_role\x18\x01 \x01(\v2\x14.permission.UserRoleR\buserRole\"'\n" +
	"\x15DeleteUserRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc7\x01\n" +
	"\x13ListUserRoleRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x128\n" +
	"\x04view\x18\x03 \x01(\x0e2$.permission.ListUserRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"z\n" +
	"\x14ListUserRoleResponse\x12:\n" +
	"\x0euser_role_list\x18\x01 \x03(\v2\x14.permission.UserRoleR\fuserRoleList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\\\n" +
	"\x1bBatchCreateUserRolesRequest\x12=\n" +
	"\brequests\x18\x01 \x03(\v2!.permission.CreateUserRoleRequestR\brequests\"S\n" +
	"\x1cBatchCreateUserRolesResponse\x123\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\v2\x14.permission.UserRoleR\tuserRoles2\x85\x01\n" +
	"\vPermService\x123\n" +
	"\x03Get\x12\x1a.permission.GetPermRequest\x1a\x10.permission.Perm\x12A\n" +
	"\x04List\x12\x1b.permission.ListPermRequest\x1a\x1c.permission.ListPermResponse2\x9e\x01\n" +
	"\x10PermGroupService\x12=\n" +
	"\x03Get\x12\x1f.permission.GetPermGroupRequest\x1a\x15.permission.PermGroup\x12K\n" +
	"\x04List\x12 .permission.ListPermGroupRequest\x1a!.permission.ListPermGroupResponse2\x96\x03\n" +
	"\vRoleService\x129\n" +
	"\x06Create\x12\x1d.permission.CreateRoleRequest\x1a\x10.permission.Role\x123\n" +
	"\x03Get\x12\x1a.permission.GetRoleRequest\x1a\x10.permission.Role\x129\n" +
	"\x06Update\x12\x1d.permission.UpdateRoleRequest\x1a\x10.permission.Role\x12?\n" +
	"\x06Delete\x12\x1d.permission.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x04List\x12\x1b.permission.ListRoleRequest\x1a\x1c.permission.ListRoleResponse\x12X\n" +
	"\vBatchCreate\x12#.permission.BatchCreateRolesRequest\x1a$.permission.BatchCreateRolesResponse2\xc6\x03\n" +
	"\x0fUserPermService\x12A\n" +
	"\x06Create\x12!.permission.CreateUserPermRequest\x1a\x14.permission.UserPerm\x12;\n" +
	"\x03Get\x12\x1e.permission.GetUserPermRequest\x1a\x14.permission.UserPerm\x12A\n" +
	"\x06Update\x12!.permission.UpdateUserPermRequest\x1a\x14.permission.UserPerm\x12C\n" +
	"\x06Delete\x12!.permission.DeleteUserPermRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x04List\x12\x1f.permission.ListUserPermRequest\x1a .permission.ListUserPermResponse\x12`\n" +
	"\vBatchCreate\x12'.permission.BatchCreateUserPermsRequest\x1a(.permission.BatchCreateUserPermsResponse2\xc6\x03\n" +
	"\x0fUserRoleService\x12A\n" +
	"\x06Create\x12!.permission.CreateUserRoleRequest\x1a\x14.permission.UserRole\x12;\n" +
	"\x03Get\x12\x1e.permission.GetUserRoleRequest\x1a\x14.permission.UserRole\x12A\n" +
	"\x06Update\x12!.permission.UpdateUserRoleRequest\x1a\x14.permission.UserRole\x12C\n" +
	"\x06Delete\x12!.permission.DeleteUserRoleRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x04List\x12\x1f.permission.ListUserRoleRequest\x1a .permission.ListUserRoleResponse\x12`\n" +
	"\vBatchCreate\x12'.permission.BatchCreateUserRolesRequest\x1a(.permission.BatchCreateUserRolesResponseB\x12Z\x10proto/permissionb\x06proto3"

var (
	file_proto_permission_permission_proto_rawDescOnce sync.Once
	file_proto_permission_permission_proto_rawDescData []byte
)

func file_proto_permission_permission_proto_rawDescGZIP() []byte {
	file_proto_permission_permission_proto_rawDescOnce.Do(func() {
		file_proto_permission_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_permission_permission_proto_rawDesc), len(file_proto_permission_permission_proto_rawDesc)))
	})
	return file_proto_permission_permission_proto_rawDescData
}

var file_proto_permission_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_proto_permission_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_permission_permission_proto_goTypes = []any{
	(GetPermRequest_View)(0),             // 0: permission.GetPermRequest.View
	(ListPermRequest_View)(0),            // 1: permission.ListPermRequest.View
	(GetPermGroupRequest_View)(0),        // 2: permission.GetPermGroupRequest.View
	(ListPermGroupRequest_View)(0),       // 3: permission.ListPermGroupRequest.View
	(GetRoleRequest_View)(0),             // 4: permission.GetRoleRequest.View
	(ListRoleRequest_View)(0),            // 5: permission.ListRoleRequest.View
	(GetUserPermRequest_View)(0),         // 6: permission.GetUserPermRequest.View
	(ListUserPermRequest_View)(0),        // 7: permission.ListUserPermRequest.View
	(GetUserRoleRequest_View)(0),         // 8: permission.GetUserRoleRequest.View
	(ListUserRoleRequest_View)(0),        // 9: permission.ListUserRoleRequest.View
	(*Perm)(nil),                         // 10: permission.Perm
	(*GetPermRequest)(nil),               // 11: permission.GetPermRequest
	(*ListPermRequest)(nil),              // 12: permission.ListPermRequest
	(*ListPermResponse)(nil),             // 13: permission.ListPermResponse
	(*PermGroup)(nil),                    // 14: permission.PermGroup
	(*GetPermGroupRequest)(nil),          // 15: permission.GetPermGroupRequest
	(*ListPermGroupRequest)(nil),         // 16: permission.ListPermGroupRequest
	(*ListPermGroupResponse)(nil),        // 17: permission.ListPermGroupResponse
	(*Role)(nil),                         // 18: permission.Role
	(*CreateRoleRequest)(nil),            // 19: permission.CreateRoleRequest
	(*GetRoleRequest)(nil),               // 20: permission.GetRoleRequest
	(*UpdateRoleRequest)(nil),            // 21: permission.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),            // 22: permission.DeleteRoleRequest
	(*ListRoleRequest)(nil),              // 23: permission.ListRoleRequest
	(*ListRoleResponse)(nil),             // 24: permission.ListRoleResponse
	(*BatchCreateRolesRequest)(nil),      // 25: permission.BatchCreateRolesRequest
	(*BatchCreateRolesResponse)(nil),     // 26: permission.BatchCreateRolesResponse
	(*UserPerm)(nil),                     // 27: permission.UserPerm
	(*CreateUserPermRequest)(nil),        // 28: permission.CreateUserPermRequest
	(*GetUserPermRequest)(nil),           // 29: permission.GetUserPermRequest
	(*UpdateUserPermRequest)(nil),        // 30: permission.UpdateUserPermRequest
	(*DeleteUserPermRequest)(nil),        // 31: permission.DeleteUserPermRequest
	(*ListUserPermRequest)(nil),          // 32: permission.ListUserPermRequest
	(*ListUserPermResponse)(nil),         // 33: permission.ListUserPermResponse
	(*BatchCreateUserPermsRequest)(nil),  // 34: permission.BatchCreateUserPermsRequest
	(*BatchCreateUserPermsResponse)(nil), // 35: permission.BatchCreateUserPermsResponse
	(*UserRole)(nil),                     // 36: permission.UserRole
	(*CreateUserRoleRequest)(nil),        // 37: permission.CreateUserRoleRequest
	(*GetUserRoleRequest)(nil),           // 38: permission.GetUserRoleRequest
	(*UpdateUserRoleRequest)(nil),        // 39: permission.UpdateUserRoleRequest
	(*DeleteUserRoleRequest)(nil),        // 40: permission.DeleteUserRoleRequest
	(*ListUserRoleRequest)(nil),          // 41: permission.ListUserRoleRequest
	(*ListUserRoleResponse)(nil),         // 42: permission.ListUserRoleResponse
	(*BatchCreateUserRolesRequest)(nil),  // 43: permission.BatchCreateUserRolesRequest
	(*BatchCreateUserRolesResponse)(nil), // 44: permission.BatchCreateUserRolesResponse
	(*wrapperspb.StringValue)(nil),       // 45: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),        // 46: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 47: google.protobuf.Empty
}
var file_proto_permission_permission_proto_depIdxs = []int32{
	45, // 0: permission.Perm.description:type_name -> google.protobuf.StringValue
	14, // 1: permission.Perm.group:type_name -> permission.PermGroup
	18, // 2: permission.Perm.roles:type_name -> permission.Role
	27, // 3: permission.Perm.user_perms:type_name -> permission.UserPerm
	0,  // 4: permission.GetPermRequest.view:type_name -> permission.GetPermRequest.View
	1,  // 5: permission.ListPermRequest.view:type_name -> permission.ListPermRequest.View
	10, // 6: permission.ListPermResponse.perm_list:type_name -> permission.Perm
	10, // 7: permission.PermGroup.perms:type_name -> permission.Perm
	2,  // 8: permission.GetPermGroupRequest.view:type_name -> permission.GetPermGroupRequest.View
	3,  // 9: permission.ListPermGroupRequest.view:type_name -> permission.ListPermGroupRequest.View
	14, // 10: permission.ListPermGroupResponse.perm_group_list:type_name -> permission.PermGroup
	45, // 11: permission.Role.color:type_name -> google.protobuf.StringValue
	45, // 12: permission.Role.description:type_name -> google.protobuf.StringValue
	46, // 13: permission.Role.created_at:type_name -> google.protobuf.Timestamp
	46, // 14: permission.Role.updated_at:type_name -> google.protobuf.Timestamp
	10, // 15: permission.Role.perms:type_name -> permission.Perm
	36, // 16: permission.Role.user_roles:type_name -> permission.UserRole
	18, // 17: permission.CreateRoleRequest.role:type_name -> permission.Role
	4,  // 18: permission.GetRoleRequest.view:type_name -> permission.GetRoleRequest.View
	18, // 19: permission.UpdateRoleRequest.role:type_name -> permission.Role
	5,  // 20: permission.ListRoleRequest.view:type_name -> permission.ListRoleRequest.View
	18, // 21: permission.ListRoleResponse.role_list:type_name -> permission.Role
	19, // 22: permission.BatchCreateRolesRequest.requests:type_name -> permission.CreateRoleRequest
	18, // 23: permission.BatchCreateRolesResponse.roles:type_name -> permission.Role
	46, // 24: permission.UserPerm.created_at:type_name -> google.protobuf.Timestamp
	46, // 25: permission.UserPerm.updated_at:type_name -> google.protobuf.Timestamp
	10, // 26: permission.UserPerm.perm:type_name -> permission.Perm
	27, // 27: permission.CreateUserPermRequest.user_perm:type_name -> permission.UserPerm
	6,  // 28: permission.GetUserPermRequest.view:type_name -> permission.GetUserPermRequest.View
	27, // 29: permission.UpdateUserPermRequest.user_perm:type_name -> permission.UserPerm
	7,  // 30: permission.ListUserPermRequest.view:type_name -> permission.ListUserPermRequest.View
	27, // 31: permission.ListUserPermResponse.user_perm_list:type_name -> permission.UserPerm
	28, // 32: permission.BatchCreateUserPermsRequest.requests:type_name -> permission.CreateUserPermRequest
	27, // 33: permission.BatchCreateUserPermsResponse.user_perms:type_name -> permission.UserPerm
	46, // 34: permission.UserRole.created_at:type_name -> google.protobuf.Timestamp
	46, // 35: permission.UserRole.updated_at:type_name -> google.protobuf.Timestamp
	18, // 36: permission.UserRole.role:type_name -> permission.Role
	36, // 37: permission.CreateUserRoleRequest.user_role:type_name -> permission.UserRole
	8,  // 38: permission.GetUserRoleRequest.view:type_name -> permission.GetUserRoleRequest.View
	36, // 39: permission.UpdateUserRoleRequest.user_role:type_name -> permission.UserRole
	9,  // 40: permission.ListUserRoleRequest.view:type_name -> permission.ListUserRoleRequest.View
	36, // 41: permission.ListUserRoleResponse.user_role_list:type_name -> permission.UserRole
	37, // 42: permission.BatchCreateUserRolesRequest.requests:type_name -> permission.CreateUserRoleRequest
	36, // 43: permission.BatchCreateUserRolesResponse.user_roles:type_name -> permission.UserRole
	11, // 44: permission.PermService.Get:input_type -> permission.GetPermRequest
	12, // 45: permission.PermService.List:input_type -> permission.ListPermRequest
	15, // 46: permission.PermGroupService.Get:input_type -> permission.GetPermGroupRequest
	16, // 47: permission.PermGroupService.List:input_type -> permission.ListPermGroupRequest
	19, // 48: permission.RoleService.Create:input_type -> permission.CreateRoleRequest
	20, // 49: permission.RoleService.Get:input_type -> permission.GetRoleRequest
	21, // 50: permission.RoleService.Update:input_type -> permission.UpdateRoleRequest
	22, // 51: permission.RoleService.Delete:input_type -> permission.DeleteRoleRequest
	23, // 52: permission.RoleService.List:input_type -> permission.ListRoleRequest
	25, // 53: permission.RoleService.BatchCreate:input_type -> permission.BatchCreateRolesRequest
	28, // 54: permission.UserPermService.Create:input_type -> permission.CreateUserPermRequest
	29, // 55: permission.UserPermService.Get:input_type -> permission.GetUserPermRequest
	30, // 56: permission.UserPermService.Update:input_type -> permission.UpdateUserPermRequest
	31, // 57: permission.UserPermService.Delete:input_type -> permission.DeleteUserPermRequest
	32, // 58: permission.UserPermService.List:input_type -> permission.ListUserPermRequest
	34, // 59: permission.UserPermService.BatchCreate:input_type -> permission.BatchCreateUserPermsRequest
	37, // 60: permission.UserRoleService.Create:input_type -> permission.CreateUserRoleRequest
	38, // 61: permission.UserRoleService.Get:input_type -> permission.GetUserRoleRequest
	39, // 62: permission.UserRoleService.Update:input_type -> permission.UpdateUserRoleRequest
	40, // 63: permission.UserRoleService.Delete:input_type -> permission.DeleteUserRoleRequest
	41, // 64: permission.UserRoleService.List:input_type -> permission.ListUserRoleRequest
	43, // 65: permission.UserRoleService.BatchCreate:input_type -> permission.BatchCreateUserRolesRequest
	10, // 66: permission.PermService.Get:output_type -> permission.Perm
	13, // 67: permission.PermService.List:output_type -> permission.ListPermResponse
	14, // 68: permission.PermGroupService.Get:output_type -> permission.PermGroup
	17, // 69: permission.PermGroupService.List:output_type -> permission.ListPermGroupResponse
	18, // 70: permission.RoleService.Create:output_type -> permission.Role
	18, // 71: permission.RoleService.Get:output_type -> permission.Role
	18, // 72: permission.RoleService.Update:output_type -> permission.Role
	47, // 73: permission.RoleService.Delete:output_type -> google.protobuf.Empty
	24, // 74: permission.RoleService.List:output_type -> permission.ListRoleResponse
	26, // 75: permission.RoleService.BatchCreate:output_type -> permission.BatchCreateRolesResponse
	27, // 76: permission.UserPermService.Create:output_type -> permission.UserPerm
	27, // 77: permission.UserPermService.Get:output_type -> permission.UserPerm
	27, // 78: permission.UserPermService.Update:output_type -> permission.UserPerm
	47, // 79: permission.UserPermService.Delete:output_type -> google.protobuf.Empty
	33, // 80: permission.UserPermService.List:output_type -> permission.ListUserPermResponse
	35, // 81: permission.UserPermService.BatchCreate:output_type -> permission.BatchCreateUserPermsResponse
	36, // 82: permission.UserRoleService.Create:output_type -> permission.UserRole
	36, // 83: permission.UserRoleService.Get:output_type -> permission.UserRole
	36, // 84: permission.UserRoleService.Update:output_type -> permission.UserRole
	47, // 85: permission.UserRoleService.Delete:output_type -> google.protobuf.Empty
	42, // 86: permission.UserRoleService.List:output_type -> permission.ListUserRoleResponse
	44, // 87: permission.UserRoleService.BatchCreate:output_type -> permission.BatchCreateUserRolesResponse
	66, // [66:88] is the sub-list for method output_type
	44, // [44:66] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_proto_permission_permission_proto_init() }
func file_proto_permission_permission_proto_init() {
	if File_proto_permission_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_permission_permission_proto_rawDesc), len(file_proto_permission_permission_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_permission_permission_proto_goTypes,
		DependencyIndexes: file_proto_permission_permission_proto_depIdxs,
		EnumInfos:         file_proto_permission_permission_proto_enumTypes,
		MessageInfos:      file_proto_permission_permission_proto_msgTypes,
	}.Build()
	File_proto_permission_permission_proto = out.File
	file_proto_permission_permission_proto_goTypes = nil
	file_proto_permission_permission_proto_depIdxs = nil
}
